### ISSUE TITLE
Padronização de fonte do texto citado

### ISSUE THREAD

**Issue by jorgesallum** [Saira-Editorial/saeb-reforcototal#1]
- [ ]  MAT 5
- [ ]  EDF 5
- [ ] ART 5
- [ ] POR 9
- [ ] ART 9
- [ ] EDF 9
- [ ] CHU 9
- [ ] CNA 9
- [ ] ING 9
- [ ] MAT 9

**Comment by felipesaira** [comment]
Como padronizar a fonte do texto?

- Com indicação de autor:
Nome do autor na ordem direta. Nome do site. Título do texto. Disponível em: link. Acesso em: 00 mês. 2023.
Exemplo: Isabela Bolzani; Raphael Martins. G1. Em viagem à China, Lula tem a missão de ampliar venda de produtos a um país em desaceleração. Disponível em: https://g1.globo.com/economia/noticia/2023/03/24/em-viagem-a-china-lula-tem-a-missao-de-ampliar-venda-de-produtos-a-um-pais-em-desaceleracao.ghtml. Acesso em: 24 mar. 2023.

- Sem indicação de autor:
Nome do site. Título do texto. Disponível em: link. Acesso em: 00 mês. 2023.
Exemplo: Agência Brasil. Lula assina decreto com regras de apoio ao setor cultural. Disponível em: https://agenciabrasil.ebc.com.br/geral/noticia/2023-03/lula-assina-decreto-com-regras-de-apoio-ao-setor-cultural. Acesso em: 24 mar. 2023.

! Atenção !
Dois-pontos depois de "Disponível em" e depois de "Acesso em".
Ponto final depois da abreviatura do nome do mês, com exceção de "maio", que entra inteiro sem ponto final.
Ponto final depois do ano da data, finalizando a fonte do texto.
