### ISSUE TITLE
Abertura em dupla com imagem 

### ISSUE THREAD

**Issue by jorgesallum** [Saira-Editorial/saeb-reforcototal#11]
Antes de cada primeiro módulo, nos volumes de 5º e de 9º ano, na abertura de um novo componente, criar uma dupla com uma imagem grande (ocupando a dupla toda) e o nome do componente bem grande (o ideal é que com o grafismo da capa). 

Assim, o primeiro módulo do componente começa na página par sempre, após essa abertura. Usar estas imagens, por ora:

* POR 5: https://br.freepik.com/fotos-gratis/criancas-felizes-juntando-as-maos_5682127.htm#query=children%20talking&position=43&from_view=search&track=ais
* ART 5: https://br.freepik.com/fotos-gratis/pintura-menino-em-idade-escolar-de-pele-escura-desenhando-com-lapis-azul-de-lado-para-a-camera-enquanto-esta-sentado-a-mesa-na-sala-sob-a-luz-do-dia_22757660.htm#query=children%20art&position=19&from_view=search&track=ais
* CHU 5: https://br.freepik.com/fotos-gratis/as-criancas-que-tem-o-divertimento-no-carrossel_854932.htm#query=children%20park&position=12&from_view=search&track=ais
* MAT 5: https://br.freepik.com/fotos-gratis/aluno-proximo-ao-quadro-negro-com-numeros_13132995.htm#page=2&query=children%20math&position=3&from_view=search&track=ais
* EDF 5: https://br.freepik.com/fotos-gratis/crianca-brincando-de-outdoorns-no-parque_21248950.htm#query=children%20exercise&position=26&from_view=search&track=ais
* CNA 5: https://br.freepik.com/fotos-gratis/menina-asiatica-segurando-planta-e-solo_5598508.htm#query=children%20nature&position=8&from_view=search&track=ais

**Comment by felipesaira** [comment]
@jorgesallum É um problema fazer isso no LaTex?

**Comment by jorgesallum** [comment]
No quinto ano tem que ter separador da disciplina.
