### ISSUE TITLE
Enumerações com letras sem `itemize`

### ISSUE THREAD

**Issue by jorgesallum** [Saira-Editorial/saeb-reforcototal#12]
Exemplo:

```
b) Incorreta. O rei decidiu se casar em consequência do ouro fabricado
pelo duende.
c) Incorreta. O duende apareceu buscando o que a moça lhe daria em troca
do favor de salvar sua vida.
d) Incorreta. O acordo de entregar o primeiro filho veio em consequência
```

**Comment by paulopompermaier** [comment]
@jorgesallum essa issue é para enumerar usando o itemize?
Porque, nesses casos em que a enumeração com letras está sem o itemize, trata-se do gabarito do professor, então todos os itens estão como texto corrido [b) Incorreta. O rei decidiu se casar em consequência do ouro fabricado
pelo duende. c) Incorreta. O duende apareceu buscando o que a moça lhe daria em troca do favor de salvar sua vida.
d) Incorreta. O acordo de entregar o primeiro filho veio em consequência] para ocupar o menor espaço possível na mancha.
