### ISSUE TITLE
Cotejo de texto citado

### ISSUE THREAD

**Issue by felipesaira** [Saira-Editorial/saeb-reforcototal#2]
- Acessar o link disponível no material diagramado.
- Cotejar o texto citado no material com o texto disponível na internet.
- Caso não haja, fazer indiações de corte desta forma: [...].

**Exemplo**
- Texto disponível na internet:
A Caixa Econômica Federal paga nesta sexta-feira (24) a parcela do novo Bolsa Família aos beneficiários com Número de Inscrição Social (NIS) de final 5. Essa é a primeira parcela com o adicional de R$ 150 a famílias com crianças de até 6 anos.
O valor mínimo corresponde a R$ 600, mas com o novo adicional o valor médio do benefício sobe para R$ 669,93. Segundo o Ministério do Desenvolvimento e Assistência Social, neste mês o programa de transferência de renda do governo federal alcançará 21,1 milhões de famílias, com gasto de R$ 14 bilhões.

- Texto citado pelo autor:
Caixa Econômica Federal paga a parcela do novo Bolsa Família aos beneficiários com Número de Inscrição Social (NIS) de final 5. É a primeira parcela com o adicional de R$ 150 a famílias com crianças de até 6 anos.

- Texto como deve ficar no material depois do cotejo:
[...] Caixa Econômica Federal paga [...] a parcela do novo Bolsa Família aos beneficiários com Número de Inscrição Social (NIS) de final 5. [...] é a primeira parcela com o adicional de R$ 150 a famílias com crianças de até 6 anos. [...]

**Comment by jorgesallum** [comment]
Passar para Ana Lancaman. Explicaremos para a @suzanasalama

**Comment by jorgesallum** [comment]
- [ ] 5ANO_MATEMATICA
- [ ] 5ANO_PORTUGUES
- [ ] 9AN0_MATEMATICA
- [ ] 9AN0_PORTUGUES

**Comment by jorgesallum** [comment]
@felipesaira @fabiasaira atualizar por favor
