### ISSUE TITLE
Posicionamento das respostas 

### ISSUE THREAD

**Issue by jorgesallum** [Saira-Editorial/saeb-reforcototal#8]
Arrumar o posicionamento das respostas e dos comentários para o professor, sem que eles ocupem espaço útil da mancha, com exceção para a seção Treino e para os simulados, em que os comentários com o gabarito aparecem na mancha após a última alternativa para o aluno. As respostas precisam aparecer no espaço correspondente para o aluno escrever.

**Comment by jorgesallum** [comment]
@fabiasaira essa é uma questão. Nós estamos trabalhando com LaTeX que é menos preciso. Seria bom discutirmos algumas possibilidades antes.

**Comment by fabiasaira** [comment]
Tranquilo, podemos repensar. O importante é definir logo qual será a opção. Se der, definimos isso hoje na reunião das 15h.

**Comment by jorgesallum** [comment]
Pronto. Fize eu pe Paulo
